version: '3.7'

services:
  postgres:
    image: "${dut_image}"
    container_name: postgres
    ports: [5432:5432]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on: 
      - bencher 

  bencher:
    build: 
      context: .
      dockerfile: Dockerfile.bencher
      args:
        base_image: "${dut_image}"
    container_name: bencher
    volumes:
      - ./benches:/home/postgres/benches

volumes:
  prom_data:
