version: '3.7'

services:
  postgres:
    image: "${dut_image}"
    container_name: postgres
    ports: [5432:5432]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 3

  postgres_bencher:
    build: ./bencher
    container_name: postgres_bencher
    environment:
      # how many could a postgres couldgres if a postgres could pres gost?
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
