version: '3.7'

services:
  postgres:
    image: "${dut_image}"
    container_name: postgres
    ports: [5432:5432]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 3
